/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desafio1.Form;

import Desafio1.PlanoCartesiano;
import Desafio1.Utils.Assets;
import Desafio1.Utils.Physics;
import java.awt.Color;
import java.util.List;
import javax.swing.JColorChooser;

/**
 *
 * @author chepito
 */
public class Conf extends javax.swing.JDialog {

    /**
     * Creates new form Configuración
     */
    
      Color[]colores = new Color[5];
      boolean[]valores = new boolean[4];
      private static int indiceCombo = 0;
    public Conf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if(PlanoCartesiano.cuadricula) this.chkCuadricula.setSelected(true);
        if(PlanoCartesiano.numeros) this.chkNum.setSelected(true);
        if(PlanoCartesiano.raya) this.chkEjes.setSelected(true);
        if(Physics.cm) this.chkCM.setSelected(true);
        
        
        this.cmbFondo.setSelectedIndex(indiceCombo);
        
        this.txtCuadricula.setBackground(Assets.colorCuadricula);
        this.txtNumero.setBackground(Assets.colorNumero);
        this.txtLinea.setBackground(Assets.colorLinea);
        this.txtCarga.setBackground(Assets.colorCarga);
        this.txtPunto.setBackground(Assets.colorPunto);
        
        
        valores[0]=Physics.cm;
        valores[1]=PlanoCartesiano.cuadricula;
        valores[2]=PlanoCartesiano.raya;
        valores[3]=PlanoCartesiano.numeros;
                
        colores[0] =Assets.colorCuadricula;
        colores[1] = Assets.colorNumero;
        colores[2]  = Assets.colorLinea;
        colores[3] = Assets.colorCarga;
        colores[4]=Assets.colorPunto; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chkCM = new javax.swing.JCheckBox();
        cmbFondo = new javax.swing.JComboBox<>();
        btnCuadricula = new javax.swing.JButton();
        txtCuadricula = new javax.swing.JTextField();
        chkCuadricula = new javax.swing.JCheckBox();
        chkEjes = new javax.swing.JCheckBox();
        chkNum = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnNumero = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLinea = new javax.swing.JButton();
        txtLinea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCarga = new javax.swing.JButton();
        txtCarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPunto = new javax.swing.JButton();
        txtPunto = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONFIGURACIÓN");

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hecho por Ariel para fisica:) ");

        chkCM.setText("Datos de entrada en CM");
        chkCM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCMItemStateChanged(evt);
            }
        });

        cmbFondo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fondo 1", "Fondo 2", "Fondo 3", "Fondo 4", "Fondo 5", "Fondo 6", "Fondo 7", "Fondo 8" }));

        btnCuadricula.setText("SELECIONAR");
        btnCuadricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadriculaActionPerformed(evt);
            }
        });

        txtCuadricula.setEnabled(false);

        chkCuadricula.setText("Mostrar Cuadricula");
        chkCuadricula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCuadriculaItemStateChanged(evt);
            }
        });

        chkEjes.setText("Mostrar ejes");
        chkEjes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkEjesItemStateChanged(evt);
            }
        });

        chkNum.setText("Mostrar Numeros");
        chkNum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkNumItemStateChanged(evt);
            }
        });

        jLabel2.setText("colorCuadricula:");

        btnNumero.setText("SELECIONAR");
        btnNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroActionPerformed(evt);
            }
        });

        txtNumero.setEnabled(false);

        jLabel3.setText("colorNumero:");

        jLabel4.setText("colorCarga:");

        btnLinea.setText("SELECIONAR");
        btnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaActionPerformed(evt);
            }
        });

        txtLinea.setEnabled(false);

        jLabel5.setText("colorEjes:");

        btnCarga.setText("SELECIONAR");
        btnCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaActionPerformed(evt);
            }
        });

        txtCarga.setEnabled(false);

        jLabel6.setText("colorPunto:");

        btnPunto.setText("SELECIONAR");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        txtPunto.setEnabled(false);

        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(btnLinea))
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(btnNumero))
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCM)
                                    .addComponent(chkEjes))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkNum)
                                    .addComponent(chkCuadricula)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1))
                            .addComponent(cmbFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(btnCuadricula))
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addComponent(txtCuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(143, 143, 143)
                                            .addComponent(btnPunto))
                                        .addComponent(jLabel6))
                                    .addGap(37, 37, 37)
                                    .addComponent(txtPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(143, 143, 143)
                                            .addComponent(btnCarga))
                                        .addComponent(jLabel4))
                                    .addGap(37, 37, 37)
                                    .addComponent(txtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(38, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCM)
                    .addComponent(chkCuadricula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEjes)
                    .addComponent(chkNum))
                .addGap(18, 18, 18)
                .addComponent(cmbFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCuadricula)
                    .addComponent(txtCuadricula)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero)
                    .addComponent(txtNumero)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinea)
                    .addComponent(txtLinea)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarga)
                    .addComponent(txtCarga)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPunto)
                    .addComponent(txtPunto)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Physics.cm = valores[0];
        PlanoCartesiano.cuadricula = valores[1];
        PlanoCartesiano.raya= valores[2];
        PlanoCartesiano.numeros = valores[3];
        indiceCombo =cmbFondo.getSelectedIndex();
        Assets.rutaImagen = Assets.FONDOS[cmbFondo.getSelectedIndex()];             
                
        Assets.colorCuadricula = colores[0];
        Assets.colorNumero =colores[1];
        Assets.colorLinea  =colores[2];
        Assets.colorCarga  =colores[3];
        Assets.colorPunto  =colores[4];        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCuadriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadriculaActionPerformed
             
        colores[0] = JColorChooser.showDialog(null, "Selecione un color", Color.RED); 
        txtCuadricula.setBackground(colores[0]);
    }//GEN-LAST:event_btnCuadriculaActionPerformed

    private void btnNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroActionPerformed
         colores[1] = JColorChooser.showDialog(null, "Selecione un color", Color.RED);
         txtNumero.setBackground(colores[1]);
    }//GEN-LAST:event_btnNumeroActionPerformed

    private void btnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaActionPerformed
         colores[2] = JColorChooser.showDialog(null, "Selecione un color", Color.RED);
         txtLinea.setBackground(colores[2]);
    }//GEN-LAST:event_btnLineaActionPerformed

    private void btnCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaActionPerformed
         colores[3] = JColorChooser.showDialog(null, "Selecione un color", Color.RED);
         txtCarga.setBackground(colores[3]);
    }//GEN-LAST:event_btnCargaActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
         colores[4] = JColorChooser.showDialog(null, "Selecione un color", Color.RED);
         txtPunto.setBackground(colores[4]);
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void chkCMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCMItemStateChanged
        valores[0] = chkCM.isSelected();        
    }//GEN-LAST:event_chkCMItemStateChanged

    private void chkCuadriculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCuadriculaItemStateChanged
        valores[1] = chkCuadricula.isSelected();  
    }//GEN-LAST:event_chkCuadriculaItemStateChanged

    private void chkEjesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkEjesItemStateChanged
         valores[2] = chkEjes.isSelected();  
    }//GEN-LAST:event_chkEjesItemStateChanged

    private void chkNumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkNumItemStateChanged
        valores[3] = chkNum.isSelected();  
    }//GEN-LAST:event_chkNumItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        indiceCombo =0;
        Assets.rutaImagen = Assets.FONDOS[0];             
        colores = new Color[5];
        valores = new boolean[4]; 
        
        Physics.cm=true;
        PlanoCartesiano.cuadricula=true;
        PlanoCartesiano.raya=true;
        PlanoCartesiano.numeros=true;
      
        Assets.colorCuadricula = new Color(49,173,215);
        Assets.colorNumero = new Color(255,255,255);
        Assets.colorLinea = new Color(255,255,255);
        Assets.colorCarga = new Color(233,30,99);
        Assets.colorPunto  = new Color(76,175,80);       
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Conf dialog = new Conf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarga;
    private javax.swing.JButton btnCuadricula;
    private javax.swing.JButton btnLinea;
    private javax.swing.JButton btnNumero;
    private javax.swing.JButton btnPunto;
    private javax.swing.JCheckBox chkCM;
    private javax.swing.JCheckBox chkCuadricula;
    private javax.swing.JCheckBox chkEjes;
    private javax.swing.JCheckBox chkNum;
    private javax.swing.JComboBox<String> cmbFondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtCuadricula;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPunto;
    // End of variables declaration//GEN-END:variables
}
